// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: watch_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Psix.Proto {

  /// <summary>Holder for reflection information generated from watch_output.proto</summary>
  public static partial class WatchOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for watch_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatchOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJ3YXRjaF9vdXRwdXQucHJvdG8aDGNvbW1vbi5wcm90byKoAQoESW5mbxIY",
            "CgRoYW5kGAEgASgOMgouSW5mby5IYW5kEg0KBWFwcElkGAIgASgJEhIKCmFw",
            "cFZlcnNpb24YAyABKAkSHwoPYXZhaWxhYmxlTW9kZWxzGAQgAygLMgYuTW9k",
            "ZWwSGwoLYWN0aXZlTW9kZWwYBSABKAsyBi5Nb2RlbCIlCgRIYW5kEggKBE5P",
            "TkUQABIJCgVSSUdIVBABEggKBExFRlQQAiKeAQoLU2Vuc29yRnJhbWUSEwoE",
            "Z3lybxgBIAEoCzIFLlZlYzMSEgoDYWNjGAIgASgLMgUuVmVjMxITCgRncmF2",
            "GAMgASgLMgUuVmVjMxITCgRxdWF0GAQgASgLMgUuUXVhdBISCgNtYWcYBiAB",
            "KAsyBS5WZWMzEhUKBm1hZ0NhbBgHIAEoCzIFLlZlYzMSEQoJZGVsdGFUaW1l",
            "GAUgASgFIjgKB0dlc3R1cmUSGgoEdHlwZRgBIAEoDjIMLkdlc3R1cmVUeXBl",
            "EhEKCWRlbHRhVGltZRgCIAEoBSLUAQoKVG91Y2hFdmVudBItCglldmVudFR5",
            "cGUYASABKA4yGi5Ub3VjaEV2ZW50LlRvdWNoRXZlbnRUeXBlEhMKC2FjdGlv",
            "bkluZGV4GAIgASgFEhIKCnBvaW50ZXJJZHMYAyADKAUSFQoGY29vcmRzGAQg",
            "AygLMgUuVmVjMhIRCglkZWx0YVRpbWUYBSABKAUiRAoOVG91Y2hFdmVudFR5",
            "cGUSCAoETk9ORRAAEgkKBUJFR0lOEAESBwoDRU5EEAISCAoETU9WRRADEgoK",
            "BkNBTkNFTBAEIi4KC1JvdGFyeUV2ZW50EgwKBHN0ZXAYASABKAUSEQoJZGVs",
            "dGFUaW1lGAIgASgFIiwKC0J1dHRvbkV2ZW50EgoKAmlkGAEgASgFEhEKCWRl",
            "bHRhVGltZRgCIAEoBSJEChBQcm9iYWJpbGl0eUVudHJ5EhsKBWxhYmVsGAEg",
            "ASgOMgwuR2VzdHVyZVR5cGUSEwoLcHJvYmFiaWxpdHkYAiABKAIimwMKBlVw",
            "ZGF0ZRIiCgxzZW5zb3JGcmFtZXMYASADKAsyDC5TZW5zb3JGcmFtZRIaCghn",
            "ZXN0dXJlcxgCIAMoCzIILkdlc3R1cmUSIAoLdG91Y2hFdmVudHMYAyADKAsy",
            "Cy5Ub3VjaEV2ZW50EiIKDGJ1dHRvbkV2ZW50cxgEIAMoCzIMLkJ1dHRvbkV2",
            "ZW50EiIKDHJvdGFyeUV2ZW50cxgFIAMoCzIMLlJvdGFyeUV2ZW50Eh8KB3Np",
            "Z25hbHMYBiADKA4yDi5VcGRhdGUuU2lnbmFsEhEKCWRlbHRhVGltZRgHIAEo",
            "BRIQCgh1bml4VGltZRgIIAEoAxITCgRpbmZvGAkgASgLMgUuSW5mbxIoCg1w",
            "cm9iYWJpbGl0aWVzGAogAygLMhEuUHJvYmFiaWxpdHlFbnRyeRIQCghwcmVz",
            "c3VyZRgQIAEoAiJQCgZTaWduYWwSCAoETk9ORRAAEg4KCkRJU0NPTk5FQ1QQ",
            "ARIUChBDT05ORUNUX0FQUFJPVkVEEAISFgoSREVTQ1JJUFRJT05fVVBEQVRF",
            "EANCDaoCClBzaXguUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Psix.Proto.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.Info), global::Psix.Proto.Info.Parser, new[]{ "Hand", "AppId", "AppVersion", "AvailableModels", "ActiveModel" }, null, new[]{ typeof(global::Psix.Proto.Info.Types.Hand) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.SensorFrame), global::Psix.Proto.SensorFrame.Parser, new[]{ "Gyro", "Acc", "Grav", "Quat", "Mag", "MagCal", "DeltaTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.Gesture), global::Psix.Proto.Gesture.Parser, new[]{ "Type", "DeltaTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.TouchEvent), global::Psix.Proto.TouchEvent.Parser, new[]{ "EventType", "ActionIndex", "PointerIds", "Coords", "DeltaTime" }, null, new[]{ typeof(global::Psix.Proto.TouchEvent.Types.TouchEventType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.RotaryEvent), global::Psix.Proto.RotaryEvent.Parser, new[]{ "Step", "DeltaTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.ButtonEvent), global::Psix.Proto.ButtonEvent.Parser, new[]{ "Id", "DeltaTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.ProbabilityEntry), global::Psix.Proto.ProbabilityEntry.Parser, new[]{ "Label", "Probability" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Psix.Proto.Update), global::Psix.Proto.Update.Parser, new[]{ "SensorFrames", "Gestures", "TouchEvents", "ButtonEvents", "RotaryEvents", "Signals", "DeltaTime", "UnixTime", "Info", "Probabilities", "Pressure" }, null, new[]{ typeof(global::Psix.Proto.Update.Types.Signal) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Info : pb::IMessage<Info>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Info> _parser = new pb::MessageParser<Info>(() => new Info());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Info> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Info() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Info(Info other) : this() {
      hand_ = other.hand_;
      appId_ = other.appId_;
      appVersion_ = other.appVersion_;
      availableModels_ = other.availableModels_.Clone();
      activeModel_ = other.activeModel_ != null ? other.activeModel_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Info Clone() {
      return new Info(this);
    }

    /// <summary>Field number for the "hand" field.</summary>
    public const int HandFieldNumber = 1;
    private global::Psix.Proto.Info.Types.Hand hand_ = global::Psix.Proto.Info.Types.Hand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Info.Types.Hand Hand {
      get { return hand_; }
      set {
        hand_ = value;
      }
    }

    /// <summary>Field number for the "appId" field.</summary>
    public const int AppIdFieldNumber = 2;
    private string appId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppId {
      get { return appId_; }
      set {
        appId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "appVersion" field.</summary>
    public const int AppVersionFieldNumber = 3;
    private string appVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppVersion {
      get { return appVersion_; }
      set {
        appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "availableModels" field.</summary>
    public const int AvailableModelsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Psix.Proto.Model> _repeated_availableModels_codec
        = pb::FieldCodec.ForMessage(34, global::Psix.Proto.Model.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.Model> availableModels_ = new pbc::RepeatedField<global::Psix.Proto.Model>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.Model> AvailableModels {
      get { return availableModels_; }
    }

    /// <summary>Field number for the "activeModel" field.</summary>
    public const int ActiveModelFieldNumber = 5;
    private global::Psix.Proto.Model activeModel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Model ActiveModel {
      get { return activeModel_; }
      set {
        activeModel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Info);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Info other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Hand != other.Hand) return false;
      if (AppId != other.AppId) return false;
      if (AppVersion != other.AppVersion) return false;
      if(!availableModels_.Equals(other.availableModels_)) return false;
      if (!object.Equals(ActiveModel, other.ActiveModel)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Hand != global::Psix.Proto.Info.Types.Hand.None) hash ^= Hand.GetHashCode();
      if (AppId.Length != 0) hash ^= AppId.GetHashCode();
      if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
      hash ^= availableModels_.GetHashCode();
      if (activeModel_ != null) hash ^= ActiveModel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Hand != global::Psix.Proto.Info.Types.Hand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Hand);
      }
      if (AppId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppId);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppVersion);
      }
      availableModels_.WriteTo(output, _repeated_availableModels_codec);
      if (activeModel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ActiveModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Hand != global::Psix.Proto.Info.Types.Hand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Hand);
      }
      if (AppId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppId);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppVersion);
      }
      availableModels_.WriteTo(ref output, _repeated_availableModels_codec);
      if (activeModel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ActiveModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Hand != global::Psix.Proto.Info.Types.Hand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hand);
      }
      if (AppId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppId);
      }
      if (AppVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
      }
      size += availableModels_.CalculateSize(_repeated_availableModels_codec);
      if (activeModel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActiveModel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Info other) {
      if (other == null) {
        return;
      }
      if (other.Hand != global::Psix.Proto.Info.Types.Hand.None) {
        Hand = other.Hand;
      }
      if (other.AppId.Length != 0) {
        AppId = other.AppId;
      }
      if (other.AppVersion.Length != 0) {
        AppVersion = other.AppVersion;
      }
      availableModels_.Add(other.availableModels_);
      if (other.activeModel_ != null) {
        if (activeModel_ == null) {
          ActiveModel = new global::Psix.Proto.Model();
        }
        ActiveModel.MergeFrom(other.ActiveModel);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Hand = (global::Psix.Proto.Info.Types.Hand) input.ReadEnum();
            break;
          }
          case 18: {
            AppId = input.ReadString();
            break;
          }
          case 26: {
            AppVersion = input.ReadString();
            break;
          }
          case 34: {
            availableModels_.AddEntriesFrom(input, _repeated_availableModels_codec);
            break;
          }
          case 42: {
            if (activeModel_ == null) {
              ActiveModel = new global::Psix.Proto.Model();
            }
            input.ReadMessage(ActiveModel);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Hand = (global::Psix.Proto.Info.Types.Hand) input.ReadEnum();
            break;
          }
          case 18: {
            AppId = input.ReadString();
            break;
          }
          case 26: {
            AppVersion = input.ReadString();
            break;
          }
          case 34: {
            availableModels_.AddEntriesFrom(ref input, _repeated_availableModels_codec);
            break;
          }
          case 42: {
            if (activeModel_ == null) {
              ActiveModel = new global::Psix.Proto.Model();
            }
            input.ReadMessage(ActiveModel);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Info message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Hand {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("RIGHT")] Right = 1,
        [pbr::OriginalName("LEFT")] Left = 2,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SensorFrame : pb::IMessage<SensorFrame>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SensorFrame> _parser = new pb::MessageParser<SensorFrame>(() => new SensorFrame());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SensorFrame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorFrame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorFrame(SensorFrame other) : this() {
      gyro_ = other.gyro_ != null ? other.gyro_.Clone() : null;
      acc_ = other.acc_ != null ? other.acc_.Clone() : null;
      grav_ = other.grav_ != null ? other.grav_.Clone() : null;
      quat_ = other.quat_ != null ? other.quat_.Clone() : null;
      mag_ = other.mag_ != null ? other.mag_.Clone() : null;
      magCal_ = other.magCal_ != null ? other.magCal_.Clone() : null;
      deltaTime_ = other.deltaTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorFrame Clone() {
      return new SensorFrame(this);
    }

    /// <summary>Field number for the "gyro" field.</summary>
    public const int GyroFieldNumber = 1;
    private global::Psix.Proto.Vec3 gyro_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Vec3 Gyro {
      get { return gyro_; }
      set {
        gyro_ = value;
      }
    }

    /// <summary>Field number for the "acc" field.</summary>
    public const int AccFieldNumber = 2;
    private global::Psix.Proto.Vec3 acc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Vec3 Acc {
      get { return acc_; }
      set {
        acc_ = value;
      }
    }

    /// <summary>Field number for the "grav" field.</summary>
    public const int GravFieldNumber = 3;
    private global::Psix.Proto.Vec3 grav_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Vec3 Grav {
      get { return grav_; }
      set {
        grav_ = value;
      }
    }

    /// <summary>Field number for the "quat" field.</summary>
    public const int QuatFieldNumber = 4;
    private global::Psix.Proto.Quat quat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Quat Quat {
      get { return quat_; }
      set {
        quat_ = value;
      }
    }

    /// <summary>Field number for the "mag" field.</summary>
    public const int MagFieldNumber = 6;
    private global::Psix.Proto.Vec3 mag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Vec3 Mag {
      get { return mag_; }
      set {
        mag_ = value;
      }
    }

    /// <summary>Field number for the "magCal" field.</summary>
    public const int MagCalFieldNumber = 7;
    private global::Psix.Proto.Vec3 magCal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Vec3 MagCal {
      get { return magCal_; }
      set {
        magCal_ = value;
      }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 5;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SensorFrame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SensorFrame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Gyro, other.Gyro)) return false;
      if (!object.Equals(Acc, other.Acc)) return false;
      if (!object.Equals(Grav, other.Grav)) return false;
      if (!object.Equals(Quat, other.Quat)) return false;
      if (!object.Equals(Mag, other.Mag)) return false;
      if (!object.Equals(MagCal, other.MagCal)) return false;
      if (DeltaTime != other.DeltaTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (gyro_ != null) hash ^= Gyro.GetHashCode();
      if (acc_ != null) hash ^= Acc.GetHashCode();
      if (grav_ != null) hash ^= Grav.GetHashCode();
      if (quat_ != null) hash ^= Quat.GetHashCode();
      if (mag_ != null) hash ^= Mag.GetHashCode();
      if (magCal_ != null) hash ^= MagCal.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (gyro_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Gyro);
      }
      if (acc_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Acc);
      }
      if (grav_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Grav);
      }
      if (quat_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Quat);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeltaTime);
      }
      if (mag_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Mag);
      }
      if (magCal_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MagCal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (gyro_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Gyro);
      }
      if (acc_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Acc);
      }
      if (grav_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Grav);
      }
      if (quat_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Quat);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeltaTime);
      }
      if (mag_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Mag);
      }
      if (magCal_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MagCal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (gyro_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gyro);
      }
      if (acc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Acc);
      }
      if (grav_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Grav);
      }
      if (quat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quat);
      }
      if (mag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mag);
      }
      if (magCal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MagCal);
      }
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SensorFrame other) {
      if (other == null) {
        return;
      }
      if (other.gyro_ != null) {
        if (gyro_ == null) {
          Gyro = new global::Psix.Proto.Vec3();
        }
        Gyro.MergeFrom(other.Gyro);
      }
      if (other.acc_ != null) {
        if (acc_ == null) {
          Acc = new global::Psix.Proto.Vec3();
        }
        Acc.MergeFrom(other.Acc);
      }
      if (other.grav_ != null) {
        if (grav_ == null) {
          Grav = new global::Psix.Proto.Vec3();
        }
        Grav.MergeFrom(other.Grav);
      }
      if (other.quat_ != null) {
        if (quat_ == null) {
          Quat = new global::Psix.Proto.Quat();
        }
        Quat.MergeFrom(other.Quat);
      }
      if (other.mag_ != null) {
        if (mag_ == null) {
          Mag = new global::Psix.Proto.Vec3();
        }
        Mag.MergeFrom(other.Mag);
      }
      if (other.magCal_ != null) {
        if (magCal_ == null) {
          MagCal = new global::Psix.Proto.Vec3();
        }
        MagCal.MergeFrom(other.MagCal);
      }
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (gyro_ == null) {
              Gyro = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Gyro);
            break;
          }
          case 18: {
            if (acc_ == null) {
              Acc = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Acc);
            break;
          }
          case 26: {
            if (grav_ == null) {
              Grav = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Grav);
            break;
          }
          case 34: {
            if (quat_ == null) {
              Quat = new global::Psix.Proto.Quat();
            }
            input.ReadMessage(Quat);
            break;
          }
          case 40: {
            DeltaTime = input.ReadInt32();
            break;
          }
          case 50: {
            if (mag_ == null) {
              Mag = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Mag);
            break;
          }
          case 58: {
            if (magCal_ == null) {
              MagCal = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(MagCal);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (gyro_ == null) {
              Gyro = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Gyro);
            break;
          }
          case 18: {
            if (acc_ == null) {
              Acc = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Acc);
            break;
          }
          case 26: {
            if (grav_ == null) {
              Grav = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Grav);
            break;
          }
          case 34: {
            if (quat_ == null) {
              Quat = new global::Psix.Proto.Quat();
            }
            input.ReadMessage(Quat);
            break;
          }
          case 40: {
            DeltaTime = input.ReadInt32();
            break;
          }
          case 50: {
            if (mag_ == null) {
              Mag = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(Mag);
            break;
          }
          case 58: {
            if (magCal_ == null) {
              MagCal = new global::Psix.Proto.Vec3();
            }
            input.ReadMessage(MagCal);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Gesture : pb::IMessage<Gesture>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Gesture> _parser = new pb::MessageParser<Gesture>(() => new Gesture());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Gesture> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gesture() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gesture(Gesture other) : this() {
      type_ = other.type_;
      deltaTime_ = other.deltaTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gesture Clone() {
      return new Gesture(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Psix.Proto.GestureType type_ = global::Psix.Proto.GestureType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.GestureType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 2;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Gesture);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Gesture other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (DeltaTime != other.DeltaTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Psix.Proto.GestureType.None) hash ^= Type.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Psix.Proto.GestureType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Psix.Proto.GestureType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Psix.Proto.GestureType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Gesture other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Psix.Proto.GestureType.None) {
        Type = other.Type;
      }
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Psix.Proto.GestureType) input.ReadEnum();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Psix.Proto.GestureType) input.ReadEnum();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TouchEvent : pb::IMessage<TouchEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TouchEvent> _parser = new pb::MessageParser<TouchEvent>(() => new TouchEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TouchEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchEvent(TouchEvent other) : this() {
      eventType_ = other.eventType_;
      actionIndex_ = other.actionIndex_;
      pointerIds_ = other.pointerIds_.Clone();
      coords_ = other.coords_.Clone();
      deltaTime_ = other.deltaTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchEvent Clone() {
      return new TouchEvent(this);
    }

    /// <summary>Field number for the "eventType" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::Psix.Proto.TouchEvent.Types.TouchEventType eventType_ = global::Psix.Proto.TouchEvent.Types.TouchEventType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.TouchEvent.Types.TouchEventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "actionIndex" field.</summary>
    public const int ActionIndexFieldNumber = 2;
    private int actionIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ActionIndex {
      get { return actionIndex_; }
      set {
        actionIndex_ = value;
      }
    }

    /// <summary>Field number for the "pointerIds" field.</summary>
    public const int PointerIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_pointerIds_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> pointerIds_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PointerIds {
      get { return pointerIds_; }
    }

    /// <summary>Field number for the "coords" field.</summary>
    public const int CoordsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Psix.Proto.Vec2> _repeated_coords_codec
        = pb::FieldCodec.ForMessage(34, global::Psix.Proto.Vec2.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.Vec2> coords_ = new pbc::RepeatedField<global::Psix.Proto.Vec2>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.Vec2> Coords {
      get { return coords_; }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 5;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TouchEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TouchEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (ActionIndex != other.ActionIndex) return false;
      if(!pointerIds_.Equals(other.pointerIds_)) return false;
      if(!coords_.Equals(other.coords_)) return false;
      if (DeltaTime != other.DeltaTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::Psix.Proto.TouchEvent.Types.TouchEventType.None) hash ^= EventType.GetHashCode();
      if (ActionIndex != 0) hash ^= ActionIndex.GetHashCode();
      hash ^= pointerIds_.GetHashCode();
      hash ^= coords_.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventType != global::Psix.Proto.TouchEvent.Types.TouchEventType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (ActionIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActionIndex);
      }
      pointerIds_.WriteTo(output, _repeated_pointerIds_codec);
      coords_.WriteTo(output, _repeated_coords_codec);
      if (DeltaTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventType != global::Psix.Proto.TouchEvent.Types.TouchEventType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (ActionIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActionIndex);
      }
      pointerIds_.WriteTo(ref output, _repeated_pointerIds_codec);
      coords_.WriteTo(ref output, _repeated_coords_codec);
      if (DeltaTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::Psix.Proto.TouchEvent.Types.TouchEventType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (ActionIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActionIndex);
      }
      size += pointerIds_.CalculateSize(_repeated_pointerIds_codec);
      size += coords_.CalculateSize(_repeated_coords_codec);
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TouchEvent other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::Psix.Proto.TouchEvent.Types.TouchEventType.None) {
        EventType = other.EventType;
      }
      if (other.ActionIndex != 0) {
        ActionIndex = other.ActionIndex;
      }
      pointerIds_.Add(other.pointerIds_);
      coords_.Add(other.coords_);
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::Psix.Proto.TouchEvent.Types.TouchEventType) input.ReadEnum();
            break;
          }
          case 16: {
            ActionIndex = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            pointerIds_.AddEntriesFrom(input, _repeated_pointerIds_codec);
            break;
          }
          case 34: {
            coords_.AddEntriesFrom(input, _repeated_coords_codec);
            break;
          }
          case 40: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventType = (global::Psix.Proto.TouchEvent.Types.TouchEventType) input.ReadEnum();
            break;
          }
          case 16: {
            ActionIndex = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            pointerIds_.AddEntriesFrom(ref input, _repeated_pointerIds_codec);
            break;
          }
          case 34: {
            coords_.AddEntriesFrom(ref input, _repeated_coords_codec);
            break;
          }
          case 40: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TouchEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum TouchEventType {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("BEGIN")] Begin = 1,
        [pbr::OriginalName("END")] End = 2,
        [pbr::OriginalName("MOVE")] Move = 3,
        [pbr::OriginalName("CANCEL")] Cancel = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RotaryEvent : pb::IMessage<RotaryEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RotaryEvent> _parser = new pb::MessageParser<RotaryEvent>(() => new RotaryEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RotaryEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RotaryEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RotaryEvent(RotaryEvent other) : this() {
      step_ = other.step_;
      deltaTime_ = other.deltaTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RotaryEvent Clone() {
      return new RotaryEvent(this);
    }

    /// <summary>Field number for the "step" field.</summary>
    public const int StepFieldNumber = 1;
    private int step_;
    /// <summary>
    /// 0 is used for None
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Step {
      get { return step_; }
      set {
        step_ = value;
      }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 2;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RotaryEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RotaryEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Step != other.Step) return false;
      if (DeltaTime != other.DeltaTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Step != 0) hash ^= Step.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Step != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Step);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Step != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Step);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Step != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Step);
      }
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RotaryEvent other) {
      if (other == null) {
        return;
      }
      if (other.Step != 0) {
        Step = other.Step;
      }
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Step = input.ReadInt32();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Step = input.ReadInt32();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ButtonEvent : pb::IMessage<ButtonEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ButtonEvent> _parser = new pb::MessageParser<ButtonEvent>(() => new ButtonEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ButtonEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonEvent(ButtonEvent other) : this() {
      id_ = other.id_;
      deltaTime_ = other.deltaTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonEvent Clone() {
      return new ButtonEvent(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// Must be non-negative for valid button. -1 is reserved for None
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 2;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ButtonEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ButtonEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DeltaTime != other.DeltaTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (DeltaTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeltaTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ButtonEvent other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            DeltaTime = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProbabilityEntry : pb::IMessage<ProbabilityEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProbabilityEntry> _parser = new pb::MessageParser<ProbabilityEntry>(() => new ProbabilityEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProbabilityEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProbabilityEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProbabilityEntry(ProbabilityEntry other) : this() {
      label_ = other.label_;
      probability_ = other.probability_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProbabilityEntry Clone() {
      return new ProbabilityEntry(this);
    }

    /// <summary>Field number for the "label" field.</summary>
    public const int LabelFieldNumber = 1;
    private global::Psix.Proto.GestureType label_ = global::Psix.Proto.GestureType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.GestureType Label {
      get { return label_; }
      set {
        label_ = value;
      }
    }

    /// <summary>Field number for the "probability" field.</summary>
    public const int ProbabilityFieldNumber = 2;
    private float probability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Probability {
      get { return probability_; }
      set {
        probability_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProbabilityEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProbabilityEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Label != other.Label) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Probability, other.Probability)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Label != global::Psix.Proto.GestureType.None) hash ^= Label.GetHashCode();
      if (Probability != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Probability);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Label != global::Psix.Proto.GestureType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Label);
      }
      if (Probability != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Probability);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Label != global::Psix.Proto.GestureType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Label);
      }
      if (Probability != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Probability);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Label != global::Psix.Proto.GestureType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Label);
      }
      if (Probability != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProbabilityEntry other) {
      if (other == null) {
        return;
      }
      if (other.Label != global::Psix.Proto.GestureType.None) {
        Label = other.Label;
      }
      if (other.Probability != 0F) {
        Probability = other.Probability;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Label = (global::Psix.Proto.GestureType) input.ReadEnum();
            break;
          }
          case 21: {
            Probability = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Label = (global::Psix.Proto.GestureType) input.ReadEnum();
            break;
          }
          case 21: {
            Probability = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Update : pb::IMessage<Update>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Update> _parser = new pb::MessageParser<Update>(() => new Update());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Update> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Psix.Proto.WatchOutputReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Update() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Update(Update other) : this() {
      sensorFrames_ = other.sensorFrames_.Clone();
      gestures_ = other.gestures_.Clone();
      touchEvents_ = other.touchEvents_.Clone();
      buttonEvents_ = other.buttonEvents_.Clone();
      rotaryEvents_ = other.rotaryEvents_.Clone();
      signals_ = other.signals_.Clone();
      deltaTime_ = other.deltaTime_;
      unixTime_ = other.unixTime_;
      info_ = other.info_ != null ? other.info_.Clone() : null;
      probabilities_ = other.probabilities_.Clone();
      pressure_ = other.pressure_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Update Clone() {
      return new Update(this);
    }

    /// <summary>Field number for the "sensorFrames" field.</summary>
    public const int SensorFramesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Psix.Proto.SensorFrame> _repeated_sensorFrames_codec
        = pb::FieldCodec.ForMessage(10, global::Psix.Proto.SensorFrame.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.SensorFrame> sensorFrames_ = new pbc::RepeatedField<global::Psix.Proto.SensorFrame>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.SensorFrame> SensorFrames {
      get { return sensorFrames_; }
    }

    /// <summary>Field number for the "gestures" field.</summary>
    public const int GesturesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Psix.Proto.Gesture> _repeated_gestures_codec
        = pb::FieldCodec.ForMessage(18, global::Psix.Proto.Gesture.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.Gesture> gestures_ = new pbc::RepeatedField<global::Psix.Proto.Gesture>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.Gesture> Gestures {
      get { return gestures_; }
    }

    /// <summary>Field number for the "touchEvents" field.</summary>
    public const int TouchEventsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Psix.Proto.TouchEvent> _repeated_touchEvents_codec
        = pb::FieldCodec.ForMessage(26, global::Psix.Proto.TouchEvent.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.TouchEvent> touchEvents_ = new pbc::RepeatedField<global::Psix.Proto.TouchEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.TouchEvent> TouchEvents {
      get { return touchEvents_; }
    }

    /// <summary>Field number for the "buttonEvents" field.</summary>
    public const int ButtonEventsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Psix.Proto.ButtonEvent> _repeated_buttonEvents_codec
        = pb::FieldCodec.ForMessage(34, global::Psix.Proto.ButtonEvent.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.ButtonEvent> buttonEvents_ = new pbc::RepeatedField<global::Psix.Proto.ButtonEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.ButtonEvent> ButtonEvents {
      get { return buttonEvents_; }
    }

    /// <summary>Field number for the "rotaryEvents" field.</summary>
    public const int RotaryEventsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Psix.Proto.RotaryEvent> _repeated_rotaryEvents_codec
        = pb::FieldCodec.ForMessage(42, global::Psix.Proto.RotaryEvent.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.RotaryEvent> rotaryEvents_ = new pbc::RepeatedField<global::Psix.Proto.RotaryEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.RotaryEvent> RotaryEvents {
      get { return rotaryEvents_; }
    }

    /// <summary>Field number for the "signals" field.</summary>
    public const int SignalsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Psix.Proto.Update.Types.Signal> _repeated_signals_codec
        = pb::FieldCodec.ForEnum(50, x => (int) x, x => (global::Psix.Proto.Update.Types.Signal) x);
    private readonly pbc::RepeatedField<global::Psix.Proto.Update.Types.Signal> signals_ = new pbc::RepeatedField<global::Psix.Proto.Update.Types.Signal>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.Update.Types.Signal> Signals {
      get { return signals_; }
    }

    /// <summary>Field number for the "deltaTime" field.</summary>
    public const int DeltaTimeFieldNumber = 7;
    private int deltaTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeltaTime {
      get { return deltaTime_; }
      set {
        deltaTime_ = value;
      }
    }

    /// <summary>Field number for the "unixTime" field.</summary>
    public const int UnixTimeFieldNumber = 8;
    private long unixTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UnixTime {
      get { return unixTime_; }
      set {
        unixTime_ = value;
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 9;
    private global::Psix.Proto.Info info_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Psix.Proto.Info Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "probabilities" field.</summary>
    public const int ProbabilitiesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Psix.Proto.ProbabilityEntry> _repeated_probabilities_codec
        = pb::FieldCodec.ForMessage(82, global::Psix.Proto.ProbabilityEntry.Parser);
    private readonly pbc::RepeatedField<global::Psix.Proto.ProbabilityEntry> probabilities_ = new pbc::RepeatedField<global::Psix.Proto.ProbabilityEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Psix.Proto.ProbabilityEntry> Probabilities {
      get { return probabilities_; }
    }

    /// <summary>Field number for the "pressure" field.</summary>
    public const int PressureFieldNumber = 16;
    private float pressure_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Pressure {
      get { return pressure_; }
      set {
        pressure_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Update);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Update other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sensorFrames_.Equals(other.sensorFrames_)) return false;
      if(!gestures_.Equals(other.gestures_)) return false;
      if(!touchEvents_.Equals(other.touchEvents_)) return false;
      if(!buttonEvents_.Equals(other.buttonEvents_)) return false;
      if(!rotaryEvents_.Equals(other.rotaryEvents_)) return false;
      if(!signals_.Equals(other.signals_)) return false;
      if (DeltaTime != other.DeltaTime) return false;
      if (UnixTime != other.UnixTime) return false;
      if (!object.Equals(Info, other.Info)) return false;
      if(!probabilities_.Equals(other.probabilities_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Pressure, other.Pressure)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sensorFrames_.GetHashCode();
      hash ^= gestures_.GetHashCode();
      hash ^= touchEvents_.GetHashCode();
      hash ^= buttonEvents_.GetHashCode();
      hash ^= rotaryEvents_.GetHashCode();
      hash ^= signals_.GetHashCode();
      if (DeltaTime != 0) hash ^= DeltaTime.GetHashCode();
      if (UnixTime != 0L) hash ^= UnixTime.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      hash ^= probabilities_.GetHashCode();
      if (Pressure != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Pressure);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      sensorFrames_.WriteTo(output, _repeated_sensorFrames_codec);
      gestures_.WriteTo(output, _repeated_gestures_codec);
      touchEvents_.WriteTo(output, _repeated_touchEvents_codec);
      buttonEvents_.WriteTo(output, _repeated_buttonEvents_codec);
      rotaryEvents_.WriteTo(output, _repeated_rotaryEvents_codec);
      signals_.WriteTo(output, _repeated_signals_codec);
      if (DeltaTime != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(DeltaTime);
      }
      if (UnixTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(UnixTime);
      }
      if (info_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Info);
      }
      probabilities_.WriteTo(output, _repeated_probabilities_codec);
      if (Pressure != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(Pressure);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      sensorFrames_.WriteTo(ref output, _repeated_sensorFrames_codec);
      gestures_.WriteTo(ref output, _repeated_gestures_codec);
      touchEvents_.WriteTo(ref output, _repeated_touchEvents_codec);
      buttonEvents_.WriteTo(ref output, _repeated_buttonEvents_codec);
      rotaryEvents_.WriteTo(ref output, _repeated_rotaryEvents_codec);
      signals_.WriteTo(ref output, _repeated_signals_codec);
      if (DeltaTime != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(DeltaTime);
      }
      if (UnixTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(UnixTime);
      }
      if (info_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Info);
      }
      probabilities_.WriteTo(ref output, _repeated_probabilities_codec);
      if (Pressure != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(Pressure);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += sensorFrames_.CalculateSize(_repeated_sensorFrames_codec);
      size += gestures_.CalculateSize(_repeated_gestures_codec);
      size += touchEvents_.CalculateSize(_repeated_touchEvents_codec);
      size += buttonEvents_.CalculateSize(_repeated_buttonEvents_codec);
      size += rotaryEvents_.CalculateSize(_repeated_rotaryEvents_codec);
      size += signals_.CalculateSize(_repeated_signals_codec);
      if (DeltaTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeltaTime);
      }
      if (UnixTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UnixTime);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      size += probabilities_.CalculateSize(_repeated_probabilities_codec);
      if (Pressure != 0F) {
        size += 2 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Update other) {
      if (other == null) {
        return;
      }
      sensorFrames_.Add(other.sensorFrames_);
      gestures_.Add(other.gestures_);
      touchEvents_.Add(other.touchEvents_);
      buttonEvents_.Add(other.buttonEvents_);
      rotaryEvents_.Add(other.rotaryEvents_);
      signals_.Add(other.signals_);
      if (other.DeltaTime != 0) {
        DeltaTime = other.DeltaTime;
      }
      if (other.UnixTime != 0L) {
        UnixTime = other.UnixTime;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::Psix.Proto.Info();
        }
        Info.MergeFrom(other.Info);
      }
      probabilities_.Add(other.probabilities_);
      if (other.Pressure != 0F) {
        Pressure = other.Pressure;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sensorFrames_.AddEntriesFrom(input, _repeated_sensorFrames_codec);
            break;
          }
          case 18: {
            gestures_.AddEntriesFrom(input, _repeated_gestures_codec);
            break;
          }
          case 26: {
            touchEvents_.AddEntriesFrom(input, _repeated_touchEvents_codec);
            break;
          }
          case 34: {
            buttonEvents_.AddEntriesFrom(input, _repeated_buttonEvents_codec);
            break;
          }
          case 42: {
            rotaryEvents_.AddEntriesFrom(input, _repeated_rotaryEvents_codec);
            break;
          }
          case 50:
          case 48: {
            signals_.AddEntriesFrom(input, _repeated_signals_codec);
            break;
          }
          case 56: {
            DeltaTime = input.ReadInt32();
            break;
          }
          case 64: {
            UnixTime = input.ReadInt64();
            break;
          }
          case 74: {
            if (info_ == null) {
              Info = new global::Psix.Proto.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 82: {
            probabilities_.AddEntriesFrom(input, _repeated_probabilities_codec);
            break;
          }
          case 133: {
            Pressure = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            sensorFrames_.AddEntriesFrom(ref input, _repeated_sensorFrames_codec);
            break;
          }
          case 18: {
            gestures_.AddEntriesFrom(ref input, _repeated_gestures_codec);
            break;
          }
          case 26: {
            touchEvents_.AddEntriesFrom(ref input, _repeated_touchEvents_codec);
            break;
          }
          case 34: {
            buttonEvents_.AddEntriesFrom(ref input, _repeated_buttonEvents_codec);
            break;
          }
          case 42: {
            rotaryEvents_.AddEntriesFrom(ref input, _repeated_rotaryEvents_codec);
            break;
          }
          case 50:
          case 48: {
            signals_.AddEntriesFrom(ref input, _repeated_signals_codec);
            break;
          }
          case 56: {
            DeltaTime = input.ReadInt32();
            break;
          }
          case 64: {
            UnixTime = input.ReadInt64();
            break;
          }
          case 74: {
            if (info_ == null) {
              Info = new global::Psix.Proto.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 82: {
            probabilities_.AddEntriesFrom(ref input, _repeated_probabilities_codec);
            break;
          }
          case 133: {
            Pressure = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Update message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Signal {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("DISCONNECT")] Disconnect = 1,
        [pbr::OriginalName("CONNECT_APPROVED")] ConnectApproved = 2,
        [pbr::OriginalName("DESCRIPTION_UPDATE")] DescriptionUpdate = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
